const planViejo = [
    {
        id: 1,
        nombre: "Ciclo de nivelación",
        anho: 1,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 2,
        nombre: "Anatomía y Fisiología General",
        anho: 1,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 3,
        nombre: "Anatomía y Fisiología del Sistema Nervioso",
        anho: 1,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 4,
        nombre: "Introducción a la Psicología",
        anho: 1,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 5,
        nombre: "Lingüística",
        anho: 1,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 6,
        nombre: "Logopedia y Ortofonía",
        anho: 1,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 7,
        nombre: "Comunicación y Lenguaje",
        anho: 2,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 8,
        nombre: "Psicología Evolutiva",
        anho: 2,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 9,
        nombre: "Clínica Neurológica",
        anho: 2,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 10,
        nombre: "Diagnóstico y Terapéutica del Lenguaje I",
        anho: 2,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 11,
        nombre: "Clínica de la Fonación",
        anho: 2,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 12,
        nombre: "Diagnóstico y Terapéutica de la Fonación I",
        anho: 2,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 13,
        nombre: "Prácticas de Primer Nivel",
        anho: 2,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 14,
        nombre: "Clínica Otológica",
        anho: 3,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 15,
        nombre: "Audiología",
        anho: 3,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 16,
        nombre: "Diagnóstico y Terapéutica del Lenguaje II",
        anho: 3,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 17,
        nombre: "Pedagogía y Didáctica ( Cuatrimestral)",
        anho: 3,
        cuatrimestral: true,
        nuevo: false,
    },
    {
        id: 18,
        nombre: "Endocrinología y Genética ( Cuatrimestral)",
        anho: 3,
        cuatrimestral: true,
        nuevo: false,
    },
    {
        id: 19,
        nombre: "Psicopatología General y Evolutiva (Cuatrimestral)",
        anho: 3,
        cuatrimestral: true,
        nuevo: false,
    },
    {
        id: 20,
        nombre: "Fonoaudiología Legal ( Cuatrimestral)",
        anho: 3,
        cuatrimestral: true,
        nuevo: false,
    },
    {
        id: 21,
        nombre: "Odontoestomatología ( Cuatrimestral)",
        anho: 3,
        cuatrimestral: true,
        nuevo: false,
    },
    {
        id: 22,
        nombre: "Prácticas de Segundo Nivel ( Cuatrimestral)",
        anho: 3,
        cuatrimestral: true,
        nuevo: false,
    },
    {
        id: 23,
        nombre: "Diagnóstico y Terapéutica de la Fonación II (Cuatrimestral)",
        anho: 4,
        cuatrimestral: true,
        nuevo: false,
    },
    {
        id: 24,
        nombre: "Clínica Otoneurológica y Laberintológica ( Cuatrimestral)",
        anho: 4,
        cuatrimestral: true,
        nuevo: false,
    },
    {
        id: 25,
        nombre: "Neurolingüística",
        anho: 4,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 26,
        nombre: "Psicolingüística",
        anho: 4,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 27,
        nombre: "Acústica y Psicoacústica",
        anho: 4,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 28,
        nombre: "Métodos y Técnicas de la Investigación",
        anho: 4,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 29,
        nombre: "Introducción a la Salud Pública",
        anho: 5,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 30,
        nombre: "Talleres Interdisciplinarios",
        anho: 5,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 31,
        nombre: "Seminario de Patología de la Voz",
        anho: 5,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 32,
        nombre: "Seminario de Audiología y Laberintología",
        anho: 5,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 33,
        nombre: "Seminario de Patología de Lenguaje",
        anho: 5,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 34,
        nombre: "Prácticas de Tercer Nivel",
        anho: 5,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 35,
        nombre: "Inglés",
        anho: 5,
        cuatrimestral: false,
        nuevo: false,
    },
    {
        id: 36,
        nombre: "Trabajo Final",
        anho: 5,
        cuatrimestral: false,
        nuevo: false,
    },
];

const planNuevo = [
    {
        id: 100,
        nombre: "Introducción a los estudios universirtarios en fonoaudiología",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 101,
        nombre: "Anátomo-fisiología general aplicada a la fonoaudiología",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 102,
        nombre: "Neurofisiología aplicada a la fonoaudiología",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 103,
        nombre: "Psicología aplicada a la fonoaudiología",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 104,
        nombre: "Ciencia, Salud y Sociedad",
        anho: 1,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 105,
        nombre: "Lingüística",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 106,
        nombre: "Eufonía",
        anho: 1,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 107,
        nombre: "Física para la Fonoaudiología",
        anho: 1,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 108,
        nombre: "FONACIÓN I",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 109,
        nombre: "MOTRICIDAD OROFACIAL I",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 110,
        nombre: "AUDICIÓN Y EQUILIBRIO I",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 111,
        nombre: "COMUNICACIÓN Y LENGUAJE I",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 112,
        nombre: "Psicología aplicada a la fonoaudiología II",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 113,
        nombre: "Salud pública",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 114,
        nombre: "Estadística",
        anho: 2,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 115,
        nombre: "Enfoques pedagógicos y educativos aplicados a la fonoaudiología",
        anho: 2,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 116,
        nombre: "Inglés",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 117,
        nombre: "FONACIÓN II",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 118,
        nombre: "MOTRICIDAD OROFACIAL II",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 119,
        nombre: "AUDICIÓN Y EQUILIBRIO II",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 120,
        nombre: "COMUNICACIÓN Y LENGUAJE II",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 121,
        nombre: "CLÍNICA NEUROLÓGICA APLICADA A LA FONOAUDIOLOGÍA ",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 122,
        nombre: "CLÍNICA DE LA FONACIÓN",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 123,
        nombre: "CLÍNICA DE LA AUDICIÓN",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 124,
        nombre: "CLÍNICA EN MOTRICIDAD OROFACIAL",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 125,
        nombre: "INFORMÁTICA",
        anho: 3,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 126,
        nombre: "FONACIÓN III ",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 127,
        nombre: "MOTRICIDAD OROFACIAL III",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 128,
        nombre: "AUDICIÓN Y EQUILIBRIO III ",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 129,
        nombre: "COMUNICACIÓN Y LENGUAJE III ",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 130,
        nombre: "PRODUCCIÓN CIENTÍFICA",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 131,
        nombre: "SALUD SOCIOCOMUNITARIA",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 132,
        nombre: "ÉTICA Y DEODONTOLOGÍA PROFESIONAL",
        anho: 4,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 133,
        nombre: "PRÁCTICAS PROFESIONALIZANTES I",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 134,
        nombre: "OPTATIVA",
        anho: 5,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 135,
        nombre: "OPTATIVA II",
        anho: 5,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 136,
        nombre: "PRACTICAS PROFESIONALIZANTES II",
        anho: 5,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 137,
        nombre: "TRABAJO FINAL",
        anho: 5,
        cuatrimestral: false,
        nuevo: true,
    },
];

let tempNuevoViejo = [
    {
        id: 100,
        nombre: "Introducción a los estudios universirtarios en fonoaudiología",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 101,
        nombre: "Anátomo-fisiología general aplicada a la fonoaudiología",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 102,
        nombre: "Neurofisiología aplicada a la fonoaudiología",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 103,
        nombre: "Psicología aplicada a la fonoaudiología",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 104,
        nombre: "Ciencia, Salud y Sociedad",
        anho: 1,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 105,
        nombre: "Lingüística",
        anho: 1,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 106,
        nombre: "Eufonía",
        anho: 1,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 107,
        nombre: "Física para la Fonoaudiología",
        anho: 1,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 108,
        nombre: "FONACIÓN I",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 109,
        nombre: "MOTRICIDAD OROFACIAL I",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 110,
        nombre: "AUDICIÓN Y EQUILIBRIO I",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 111,
        nombre: "COMUNICACIÓN Y LENGUAJE I",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 112,
        nombre: "Psicología aplicada a la fonoaudiología II",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 113,
        nombre: "Salud pública",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 114,
        nombre: "Estadística",
        anho: 2,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 115,
        nombre: "Enfoques pedagógicos y educativos aplicados a la fonoaudiología",
        anho: 2,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 116,
        nombre: "Inglés",
        anho: 2,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 117,
        nombre: "FONACIÓN II",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 118,
        nombre: "MOTRICIDAD OROFACIAL II",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 119,
        nombre: "AUDICIÓN Y EQUILIBRIO II",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 120,
        nombre: "COMUNICACIÓN Y LENGUAJE II",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 121,
        nombre: "CLÍNICA NEUROLÓGICA APLICADA A LA FONOAUDIOLOGÍA ",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 122,
        nombre: "CLÍNICA DE LA FONACIÓN",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 123,
        nombre: "CLÍNICA DE LA AUDICIÓN",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 124,
        nombre: "CLÍNICA EN MOTRICIDAD OROFACIAL",
        anho: 3,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 125,
        nombre: "INFORMÁTICA",
        anho: 3,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 126,
        nombre: "FONACIÓN III ",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 127,
        nombre: "MOTRICIDAD OROFACIAL III",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 128,
        nombre: "AUDICIÓN Y EQUILIBRIO III ",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 129,
        nombre: "COMUNICACIÓN Y LENGUAJE III ",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 130,
        nombre: "PRODUCCIÓN CIENTÍFIC",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 131,
        nombre: "SALUD SOCIOCOMUNITARIA",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 132,
        nombre: "ÉTICA Y DEODONTOLOGÍA PROFESIONAL",
        anho: 4,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 133,
        nombre: "PRÁCTICAS PROFESIONALIZANTES I",
        anho: 4,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 134,
        nombre: "OPTATIVA",
        anho: 5,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 135,
        nombre: "OPTATIVA II",
        anho: 5,
        cuatrimestral: true,
        nuevo: true,
    },
    {
        id: 136,
        nombre: "PRACTICAS PROFESIONALIZANTES II",
        anho: 5,
        cuatrimestral: false,
        nuevo: true,
    },
    {
        id: 137,
        nombre: "TRABAJO FINAL",
        anho: 5,
        cuatrimestral: false,
        nuevo: true,
    },
];

const puente = [
    {
        id_viejo: 1,
        id_nuevo: [100, 104],
    },
    {
        id_viejo: 2,
        id_nuevo: [101],
    },
    {
        id_viejo: 3,
        id_nuevo: [102],
    },
    {
        id_viejo: 4,
        id_nuevo: [103],
    },
    {
        id_viejo: 5,
        id_nuevo: [105],
    },
    {
        id_viejo: 6,
        id_nuevo: [106, 109],
    },
    {
        id_viejo: 7,
        id_nuevo: [111],
    },
    {
        id_viejo: 8,
        id_nuevo: [112],
    },
    {
        id_viejo: 9,
        id_nuevo: [121],
    },
    {
        id_viejo: 10,
        id_nuevo: [120],
    },
    {
        id_viejo: 11,
        id_nuevo: [122],
    },
    {
        id_viejo: 12,
        id_nuevo: [106, 108],
    },
    {
        id_viejo: 13,
        id_nuevo: [133],
    },
    {
        id_viejo: 14,
        id_nuevo: [123],
    },
    {
        id_viejo: 15,
        id_nuevo: [110, 119, 128],
    },
    {
        id_viejo: 16,
        id_nuevo: [120, 129],
    },
    {
        id_viejo: 17,
        id_nuevo: [115],
    },
    {
        id_viejo: 18,
        id_nuevo: [134],
    },
    {
        id_viejo: 19,
        id_nuevo: [112],
    },
    {
        id_viejo: 20,
        id_nuevo: [132],
    },
    {
        id_viejo: 21,
        id_nuevo: [118, 127],
    },
    {
        id_viejo: 22,
        id_nuevo: [133],
    },
    {
        id_viejo: 23,
        id_nuevo: [117, 126],
    },
    {
        id_viejo: 24,
        id_nuevo: [128],
    },
    {
        id_viejo: 25,
        id_nuevo: [129],
    },
    {
        id_viejo: 26,
        id_nuevo: [129],
    },
    {
        id_viejo: 27,
        id_nuevo: [107],
    },
    {
        id_viejo: 28,
        id_nuevo: [114, 130],
    },
    {
        id_viejo: 29,
        id_nuevo: [113, 131],
    },
    {
        id_viejo: 30,
        id_nuevo: [134],
    },
    {
        id_viejo: 31,
        id_nuevo: [135],
    },
    {
        id_viejo: 32,
        id_nuevo: [135],
    },
    {
        id_viejo: 33,
        id_nuevo: [135],
    },
    {
        id_viejo: 34,
        id_nuevo: [136],
    },
    {
        id_viejo: 35,
        id_nuevo: [116],
    },
    {
        id_viejo: 36,
        id_nuevo: [137],
    },
];

const bg = [
    "bg-fono-primero",
    "bg-fono-segundo",
    "bg-fono-tercero",
    "bg-fono-cuarto",
    "bg-fono-quinto",
];
